package ir.hooshamoozan.chatyar.ui

import androidx.compose.runtime.staticCompositionLocalOf
import ir.hooshamoozan.chatyar.data.AppLanguage

data class AppText(
    val appName: String,
    val tagline: String,
    val onboardingTitle: String,
    val onboardingBody: String,
    val onboardingPrivacyTitle: String,
    val onboardingPrivacyBody: String,
    val onboardingProviderTitle: String,
    val onboardingProviderBody: String,
    val onboardingLocalTitle: String,
    val onboardingLocalBody: String,
    val understood: String,
    val chats: String,
    val providers: String,
    val settings: String,
    val noProvidersTitle: String,
    val noProvidersBody: String,
    val addProvider: String,
    val editProvider: String,
    val providerName: String,
    val providerType: String,
    val baseUrl: String,
    val apiKey: String,
    val model: String,
    val endpointPath: String,
    val authHeader: String,
    val authPrefix: String,
    val extraHeaders: String,
    val advanced: String,
    val temperature: String,
    val maxTokens: String,
    val timeout: String,
    val streaming: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val testConnection: String,
    val testing: String,
    val connectionOk: String,
    val modelsFound: String,
    val fillRequired: String,
    val invalidJson: String,
    val providerSaved: String,
    val newChat: String,
    val noChatsTitle: String,
    val noChatsBody: String,
    val chooseProvider: String,
    val systemPrompt: String,
    val optional: String,
    val create: String,
    val messageHint: String,
    val send: String,
    val stop: String,
    val emptyChat: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val persian: String,
    val english: String,
    val telegramChannel: String,
    val telegramSubtitle: String,
    val privacyTitle: String,
    val privacyBody: String,
    val apiKeySecure: String,
    val cleartextWarning: String,
    val errorUnauthorized: String,
    val errorForbidden: String,
    val errorNotFound: String,
    val errorRateLimit: String,
    val errorServer: String,
    val errorNetwork: String,
    val errorGeneric: String,
    val protocolOpenAiResponses: String,
    val protocolOpenAi: String,
    val protocolAnthropic: String,
    val protocolGemini: String,
    val presetProviders: String,
    val customProvider: String,
    val edit: String,
    val modelRequired: String,
    val keyMayBeEmpty: String,
    val localEndpointNote: String,
    val noModelList: String,
    val providerInUseDeleteWarning: String,
    val dismiss: String
)

private val Fa = AppText(
    appName = "چتیار",
    tagline = "گفتگوی خصوصی با API خودت",
    onboardingTitle = "چتیار چطور کار می‌کند؟",
    onboardingBody = "چتیار یک کلاینت BYOK است؛ یعنی کلید API را خودت وارد می‌کنی و درخواست‌ها مستقیم از گوشی به ارائه‌دهنده ارسال می‌شوند.",
    onboardingPrivacyTitle = "کلیدها امن می‌مانند",
    onboardingPrivacyBody = "کلید API با Android Keystore رمزگذاری می‌شود و تاریخچه گفتگو به صورت محلی روی دستگاه نگهداری می‌شود.",
    onboardingProviderTitle = "هر ارائه‌دهنده‌ای که خواستی",
    onboardingProviderBody = "OpenAI، Claude، Gemini، OpenRouter، Groq، Mistral، Ollama، LM Studio و هر API سازگار با OpenAI قابل اضافه کردن است.",
    onboardingLocalTitle = "کنترل دست خودت است",
    onboardingLocalBody = "مدل، Base URL، هدرها، دما، حداکثر توکن، تایم‌اوت و Streaming قابل تنظیم هستند.",
    understood = "فهمیدم",
    chats = "گفتگوها",
    providers = "پرووایدرها",
    settings = "تنظیمات",
    noProvidersTitle = "هنوز پرووایدری اضافه نکردی",
    noProvidersBody = "برای شروع یک سرویس آماده انتخاب کن یا Base URL و کلید API دلخواهت را وارد کن.",
    addProvider = "اضافه کردن پرووایدر",
    editProvider = "ویرایش پرووایدر",
    providerName = "نام نمایشی",
    providerType = "نوع API",
    baseUrl = "Base URL",
    apiKey = "API Key",
    model = "مدل",
    endpointPath = "مسیر API",
    authHeader = "هدر احراز هویت",
    authPrefix = "پیشوند کلید",
    extraHeaders = "هدرهای اضافه (JSON)",
    advanced = "تنظیمات پیشرفته",
    temperature = "Temperature",
    maxTokens = "حداکثر توکن خروجی",
    timeout = "Timeout (ثانیه)",
    streaming = "نمایش پاسخ به صورت زنده",
    save = "ذخیره",
    cancel = "لغو",
    delete = "حذف",
    testConnection = "تست اتصال و دریافت مدل‌ها",
    testing = "در حال تست…",
    connectionOk = "اتصال موفق بود",
    modelsFound = "مدل دریافت شد",
    fillRequired = "نام، Base URL و مدل را کامل کن.",
    invalidJson = "JSON هدرهای اضافه معتبر نیست.",
    providerSaved = "پرووایدر ذخیره شد.",
    newChat = "گفتگوی جدید",
    noChatsTitle = "هنوز گفتگویی نداری",
    noChatsBody = "یک گفتگوی جدید بساز و پرووایدر موردنظرت را انتخاب کن.",
    chooseProvider = "انتخاب پرووایدر",
    systemPrompt = "System Prompt",
    optional = "اختیاری",
    create = "ساخت گفتگو",
    messageHint = "پیامت را بنویس…",
    send = "ارسال",
    stop = "توقف",
    emptyChat = "یک پیام بفرست تا گفتگو شروع شود.",
    theme = "ظاهر",
    themeSystem = "مطابق سیستم",
    themeLight = "روشن",
    themeDark = "تاریک",
    language = "زبان",
    persian = "فارسی",
    english = "English",
    telegramChannel = "کانال تلگرام",
    telegramSubtitle = "t.me/hooshamoozan",
    privacyTitle = "حریم خصوصی",
    privacyBody = "چت‌ها داخل دیتابیس محلی برنامه هستند. چتیار سرور واسط ندارد و محتوای گفتگو را برای خودش ارسال نمی‌کند.",
    apiKeySecure = "API Key در Android Keystore رمزگذاری می‌شود.",
    cleartextWarning = "برای Ollama و LM Studio روی شبکه محلی، HTTP فعال است. کلید API واقعی را به آدرس HTTP ناشناس نفرست.",
    errorUnauthorized = "کلید API رد شد (401). کلید و هدر احراز هویت را بررسی کن.",
    errorForbidden = "دسترسی مجاز نیست (403). سطح دسترسی کلید یا حساب را بررسی کن.",
    errorNotFound = "آدرس، مسیر API یا نام مدل پیدا نشد (404).",
    errorRateLimit = "محدودیت درخواست یا اعتبار حساب فعال شده (429). کمی بعد دوباره امتحان کن.",
    errorServer = "سرور ارائه‌دهنده خطا داد. چند لحظه بعد دوباره امتحان کن.",
    errorNetwork = "اتصال شبکه برقرار نشد. اینترنت، Base URL و Timeout را بررسی کن.",
    errorGeneric = "درخواست ناموفق بود.",
    protocolOpenAiResponses = "OpenAI Responses",
    protocolOpenAi = "OpenAI-compatible",
    protocolAnthropic = "Anthropic / Claude",
    protocolGemini = "Google Gemini",
    presetProviders = "ارائه‌دهندگان آماده",
    customProvider = "پرووایدر سفارشی",
    edit = "ویرایش",
    modelRequired = "نام مدل لازم است. می‌توانی با دکمه تست، لیست مدل‌ها را بگیری.",
    keyMayBeEmpty = "برای سرویس‌های لوکال بدون کلید می‌توانی این فیلد را خالی بگذاری.",
    localEndpointNote = "روی شبیه‌ساز Android، 10.0.2.2 به کامپیوتر میزبان اشاره می‌کند. روی گوشی واقعی IP شبکه کامپیوتر را وارد کن.",
    noModelList = "اتصال برقرار شد اما لیست مدلی برنگشت.",
    providerInUseDeleteWarning = "با حذف پرووایدر، گفتگوهای وابسته به آن هم حذف می‌شوند.",
    dismiss = "بستن"
)

private val En = AppText(
    appName = "Chatyar",
    tagline = "Private chat with your own API",
    onboardingTitle = "How Chatyar works",
    onboardingBody = "Chatyar is a BYOK client. You provide the API key and requests go directly from your phone to the selected provider.",
    onboardingPrivacyTitle = "Your keys stay protected",
    onboardingPrivacyBody = "API keys are encrypted with Android Keystore and chat history is stored locally on your device.",
    onboardingProviderTitle = "Use the provider you want",
    onboardingProviderBody = "OpenAI, Claude, Gemini, OpenRouter, Groq, Mistral, Ollama, LM Studio and custom OpenAI-compatible APIs are supported.",
    onboardingLocalTitle = "You control the stack",
    onboardingLocalBody = "Model, base URL, headers, temperature, max tokens, timeout and streaming are configurable.",
    understood = "Got it",
    chats = "Chats",
    providers = "Providers",
    settings = "Settings",
    noProvidersTitle = "No provider yet",
    noProvidersBody = "Pick a preset or add your own base URL and API key to get started.",
    addProvider = "Add provider",
    editProvider = "Edit provider",
    providerName = "Display name",
    providerType = "API protocol",
    baseUrl = "Base URL",
    apiKey = "API Key",
    model = "Model",
    endpointPath = "API path",
    authHeader = "Auth header",
    authPrefix = "Key prefix",
    extraHeaders = "Extra headers (JSON)",
    advanced = "Advanced settings",
    temperature = "Temperature",
    maxTokens = "Max output tokens",
    timeout = "Timeout (seconds)",
    streaming = "Stream responses",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    testConnection = "Test connection & fetch models",
    testing = "Testing…",
    connectionOk = "Connection successful",
    modelsFound = "models found",
    fillRequired = "Complete name, Base URL and model.",
    invalidJson = "Extra headers must be valid JSON.",
    providerSaved = "Provider saved.",
    newChat = "New chat",
    noChatsTitle = "No chats yet",
    noChatsBody = "Create a new chat and select the provider you want to use.",
    chooseProvider = "Choose provider",
    systemPrompt = "System prompt",
    optional = "Optional",
    create = "Create chat",
    messageHint = "Write a message…",
    send = "Send",
    stop = "Stop",
    emptyChat = "Send a message to start the conversation.",
    theme = "Appearance",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    persian = "فارسی",
    english = "English",
    telegramChannel = "Telegram channel",
    telegramSubtitle = "t.me/hooshamoozan",
    privacyTitle = "Privacy",
    privacyBody = "Chats are stored in the app's local database. Chatyar has no middleman server and does not send chat content to itself.",
    apiKeySecure = "API keys are encrypted with Android Keystore.",
    cleartextWarning = "HTTP is enabled for local Ollama and LM Studio endpoints. Never send a real API key to an untrusted HTTP endpoint.",
    errorUnauthorized = "The API key was rejected (401). Check the key and auth header.",
    errorForbidden = "Access denied (403). Check account/key permissions.",
    errorNotFound = "Base URL, API path or model was not found (404).",
    errorRateLimit = "Rate limit or account quota reached (429). Try again later.",
    errorServer = "The provider returned a server error. Try again shortly.",
    errorNetwork = "Network connection failed. Check internet, Base URL and timeout.",
    errorGeneric = "The request failed.",
    protocolOpenAiResponses = "OpenAI Responses",
    protocolOpenAi = "OpenAI-compatible",
    protocolAnthropic = "Anthropic / Claude",
    protocolGemini = "Google Gemini",
    presetProviders = "Provider presets",
    customProvider = "Custom provider",
    edit = "Edit",
    modelRequired = "A model name is required. Use the test button to fetch available models.",
    keyMayBeEmpty = "For local services without authentication, this field can stay empty.",
    localEndpointNote = "On the Android emulator, 10.0.2.2 points to the host computer. On a real phone, enter your computer's LAN IP.",
    noModelList = "Connection worked, but no model list was returned.",
    providerInUseDeleteWarning = "Deleting this provider also deletes chats that use it.",
    dismiss = "Dismiss"
)

fun textsFor(language: AppLanguage): AppText = if (language == AppLanguage.FA) Fa else En

val LocalAppText = staticCompositionLocalOf { En }
